import os
import io
import glob
from zipfile import ZipFile

import streamlit as st
from PIL import Image

st.set_page_config(page_title="Image Captioning Pro", layout="wide")

# ── Sidebar: model selection ──────────────────────────────────────────────────
st.sidebar.title("Settings")
model_choice = st.sidebar.radio(
    "Captioning model",
    ["ViT-GPT2 (Pre-trained)", "CNN+RNN (Custom Trained)"],
)

# ── ViT-GPT2 branch ───────────────────────────────────────────────────────────
if model_choice == "ViT-GPT2 (Pre-trained)":
    st.sidebar.markdown("---")
    st.sidebar.subheader("Generation Parameters")
    max_length  = st.sidebar.slider("Max Caption Length", 10,  50,  16,  1)
    num_beams   = st.sidebar.slider("Number of Beams",     1,  10,   4,  1)
    temperature = st.sidebar.slider("Temperature",       0.7, 1.5, 1.0, 0.1)
    top_k       = st.sidebar.slider("Top-k",               0, 100,  50,  1)
    top_p       = st.sidebar.slider("Top-p",             0.0, 1.0, 0.9, 0.1)

    st.sidebar.markdown("""
### About ViT-GPT2
Uses `nlpconnect/vit-gpt2-image-captioning` from HuggingFace:
- **ViT** encodes the image into patch embeddings
- **GPT-2** auto-regressively generates the caption
- No training required — weights download on first run
    """)

    @st.cache_resource
    def load_vit_gpt2():
        from src.models.vit_gpt2 import ViTGPT2Captioner
        return ViTGPT2Captioner()

    captioner        = load_vit_gpt2()
    cnn_rnn_predictor = None

# ── CNN+RNN branch ────────────────────────────────────────────────────────────
else:
    st.sidebar.markdown("---")
    st.sidebar.subheader("Checkpoint Settings")
    config_path = st.sidebar.text_input("Config path",    "configs/config.yaml")
    ckpt_dir    = st.sidebar.text_input("Checkpoint dir", "checkpoints/")

    st.sidebar.markdown("""
### About CNN+RNN
Your custom-trained model:
- **Encoder**: CNN backbone (Xception / InceptionV3 / VGG16 / ResNet50)
- **Decoder**: Stacked LSTM/GRU with attention (Bahdanau / Dot / Scaled-Dot / RAN)
- Requires a completed training run and saved checkpoint weights
    """)

    _NUM_FEATURES = {"Xception": 100, "InceptionV3": 64, "VGG16": 49, "ResNet50": 49}
    _IMG_SIZES    = {
        "Xception": (299, 299), "InceptionV3": (299, 299),
        "VGG16": (224, 224),    "ResNet50":    (224, 224),
    }

    @st.cache_resource
    def load_cnn_rnn(cfg_path, chk_dir):
        import tensorflow as tf
        from src.utils.config_loader import load_config
        from src.models.encoder import CNN_Encoder
        from src.models.decoder import RNN_Decoder
        from src.data.text_processor import TextProcessor

        config  = load_config(cfg_path)
        encoder = CNN_Encoder(config)
        decoder = RNN_Decoder(config)

        enc_name = config['model']['encoder_name']
        units    = config['model']['units']
        num_f    = _NUM_FEATURES.get(enc_name, 100)
        h, w     = _IMG_SIZES.get(enc_name, (299, 299))

        # Build weight shapes before loading saved weights
        encoder(tf.zeros((1, h, w, 3)))
        decoder(
            tf.zeros((1, 1)),
            tf.zeros((1, num_f, units)),
            decoder.init_decoder_state(tf.zeros((1, num_f, units))),
        )

        tok_files = sorted(glob.glob(os.path.join(chk_dir, "*_tokenizer.json")))
        enc_files = sorted(glob.glob(os.path.join(chk_dir, "*_enc.weights.h5")))
        dec_files = sorted(glob.glob(os.path.join(chk_dir, "*_dec.weights.h5")))

        if not tok_files or not enc_files or not dec_files:
            return None, None, None, None

        text_proc = TextProcessor(config)
        text_proc.load_tokenizer(tok_files[-1])
        encoder.load_weights(enc_files[-1])
        decoder.load_weights(dec_files[-1])

        return encoder, decoder, text_proc, config

    enc, dec, tp, cfg = load_cnn_rnn(config_path, ckpt_dir)
    captioner = None

    if enc is not None:
        from src.inference.predict import CNNRNNPredictor
        cnn_rnn_predictor = CNNRNNPredictor(enc, dec, tp, cfg)
    else:
        cnn_rnn_predictor = None
        st.sidebar.warning("No checkpoint found — run training first or adjust the directory.")

# ── Main UI ───────────────────────────────────────────────────────────────────
st.title("Image Captioning Pro")
st.write("Upload images to get captions generated by the selected model.")

uploaded_files = st.file_uploader(
    "Choose images...", type=["jpg", "jpeg", "png"], accept_multiple_files=True
)

if uploaded_files:
    results = []

    for uploaded_file in uploaded_files:
        try:
            image = Image.open(uploaded_file).convert("RGB")
            st.image(image, caption=uploaded_file.name, use_container_width=True)

            with st.spinner("Generating caption..."):
                if model_choice == "ViT-GPT2 (Pre-trained)":
                    caption = captioner.generate_caption(
                        image, max_length, num_beams, temperature, top_k, top_p
                    )
                else:
                    if cnn_rnn_predictor is None:
                        st.error("Model not loaded. Check checkpoint directory.")
                        continue
                    caption = cnn_rnn_predictor.predict(image)

            st.write(f"**Generated Caption:** {caption}")
            results.append((uploaded_file.name, image, caption))

        except Exception as e:
            st.error(f"Error processing {uploaded_file.name}: {e}")

    if results:
        buf = io.BytesIO()
        with ZipFile(buf, "w") as zf:
            for img_name, img, cap in results:
                img_bytes = io.BytesIO()
                img.save(img_bytes, format="JPEG")
                stem = os.path.splitext(img_name)[0]
                zf.writestr(f"{stem}.jpg", img_bytes.getvalue())
                zf.writestr(f"{stem}.txt", cap)
        buf.seek(0)
        st.download_button(
            "Download Captions & Images",
            buf,
            "captions_and_images.zip",
            "application/zip",
        )
else:
    st.info("Please upload image files (jpg, jpeg, png).")
