import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer

# --- NLTK Resource Management ---
# This block ensures that anyone who clones your repo has the required NLTK data.
try:
    nltk.data.find('corpora/wordnet')
    nltk.data.find('corpora/omw-1.4')
    nltk.data.find('tokenizers/punkt')
except LookupError:
    print("📥 Downloading required NLTK resources...")
    nltk.download('wordnet', quiet=True)
    nltk.download('omw-1.4', quiet=True)
    nltk.download('punkt', quiet=True)

def calculate_all_metrics(real_caption, predicted_caption):
    """
    Calculates BLEU 1-4, METEOR, and ROUGE-L.
    
    Args:
        real_caption (str): The ground truth caption from MS-COCO.
        predicted_caption (str): The caption generated by your model.
        
    Returns: 
        tuple: (bleu_tuple, meteor_score, rouge_l_score)
    """
    
    # 1. Clean the text: remove boundary tokens and extra spaces
    real_clean = real_caption.replace('<start>', '').replace('<end>', '').strip().lower()
    pred_clean = predicted_caption.replace('<start>', '').replace('<end>', '').strip().lower()

    # 2. Tokenize into words
    real_words = real_clean.split()
    pred_words = pred_clean.split()

    # SAFETY CHECK: If the model generated nothing, return zero scores
    if len(pred_words) == 0:
        return (0.0, 0.0, 0.0, 0.0), 0.0, 0.0

    # 3. BLEU Scores (1-gram through 4-gram)
    # Using SmoothingFunction is essential for short captions
    smooth = SmoothingFunction().method1
    
    b1 = sentence_bleu([real_words], pred_words, weights=(1, 0, 0, 0), smoothing_function=smooth)
    b2 = sentence_bleu([real_words], pred_words, weights=(0.5, 0.5, 0, 0), smoothing_function=smooth)
    b3 = sentence_bleu([real_words], pred_words, weights=(0.33, 0.33, 0.33, 0), smoothing_function=smooth)
    b4 = sentence_bleu([real_words], pred_words, weights=(0.25, 0.25, 0.25, 0.25), smoothing_function=smooth)

    # 4. ROUGE-L (Longest Common Subsequence)
    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)
    rouge_results = scorer.score(real_clean, pred_clean)
    rouge_l = rouge_results['rougeL'].fmeasure

    # 5. METEOR (Matches based on synonyms and stems)
    # NLTK meteor_score expects a list of references, where each reference is a list of tokens
    m_score = meteor_score([real_words], pred_words)

    return (b1, b2, b3, b4), m_score, rouge_l