dataset:
  name: "MS-COCO-2014"
  url_annotations: "http://images.cocodataset.org/annotations/annotations_trainval2014.zip"
  image_dir: "data/train2014"
  caption_file: "data/annotations/captions_train2014.json"
  image_prefix: "COCO_train2014_" 
  vocab_size: 5000
  max_caption_length: 25

model:
  encoder_name: "InceptionV3"
  decoder_type: "GRU"    # Options: LSTM, GRU
  num_layers: 3          # This controls the "Stack"
  units: 512
  embedding_dim: 256