dataset:
  name: "MS-COCO-2014"
  url_annotations: "http://images.cocodataset.org/annotations/annotations_trainval2014.zip"
  image_dir: "data/train2014"
  caption_file: "data/annotations/captions_train2014.json"
  image_prefix: "COCO_train2014_"
  vocab_size: 10000
  max_caption_length: 25
  subset_size: 50000

model:
  encoder_name: "Xception"
  decoder_type: "LSTM"
  num_layers: 3
  units: 512
  embedding_dim: 256
  # --- PHASE 3 SETTING ---
  # Options: "bahdanau", "dot", "scaled_dot"
  attention_type: "ran" 

training:
  epochs: 50
  batch_size: 128
  learning_rate: 0.0005
  use_teacher_forcing: True # Keep this TRUE for Attention stability
  checkpoint_path: "/content/drive/MyDrive/Image_Captioning_Models/checkpoints/"

mlflow:
  tracking_uri: "https://dagshub.com/enesdemir0/image-captioning-pro.mlflow"
  repo_owner: "enesdemir0"
  repo_name: "image-captioning-pro"